-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-27 20:12:10 ICT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE dosen (
    id_dosen   VARCHAR2(10 CHAR) NOT NULL,
    nama_dosen VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE dosen ADD CONSTRAINT dosen_pk PRIMARY KEY ( id_dosen );

CREATE TABLE jadwal (
    id_jadwal             VARCHAR2(25 CHAR) NOT NULL,
    hari                  VARCHAR2(10 BYTE) NOT NULL,
    tanggal               VARCHAR2(15 CHAR) NOT NULL,
    keterangan            VARCHAR2(50 CHAR) NOT NULL,
    nama_peminjam         VARCHAR2(30 CHAR) NOT NULL,
    status                VARCHAR2(15 CHAR) NOT NULL,
    ruangan_id_ruangan    VARCHAR2(25 CHAR) NOT NULL,
    mata_kuliah_id_matkul VARCHAR2(10 CHAR) NOT NULL,
    dosen_id_dosen        VARCHAR2(10 CHAR) NOT NULL
);

ALTER TABLE jadwal ADD CONSTRAINT jadwal_pk PRIMARY KEY ( id_jadwal );

CREATE TABLE mata_kuliah (
    id_matkul   VARCHAR2(10 CHAR) NOT NULL,
    nama_matkul VARCHAR2(40 CHAR) NOT NULL
);

ALTER TABLE mata_kuliah ADD CONSTRAINT mata_kuliah_pk PRIMARY KEY ( id_matkul );

CREATE TABLE ruangan (
    id_ruangan VARCHAR2(25 CHAR) NOT NULL,
    lokasi     VARCHAR2(30 CHAR) NOT NULL,
    fasilitas  VARCHAR2(255 CHAR) NOT NULL,
    jenis      VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE ruangan ADD CONSTRAINT ruangan_pk PRIMARY KEY ( id_ruangan );

ALTER TABLE jadwal
    ADD CONSTRAINT jadwal_dosen_fk FOREIGN KEY ( dosen_id_dosen )
        REFERENCES dosen ( id_dosen );

ALTER TABLE jadwal
    ADD CONSTRAINT jadwal_mata_kuliah_fk FOREIGN KEY ( mata_kuliah_id_matkul )
        REFERENCES mata_kuliah ( id_matkul );

ALTER TABLE jadwal
    ADD CONSTRAINT jadwal_ruangan_fk FOREIGN KEY ( ruangan_id_ruangan )
        REFERENCES ruangan ( id_ruangan );

